<?php
return array(
	'INVITES-enabled' => false,
	'INVITES-Auth-include' => '1',
	'INVITES-dbVersion' => '1.0.0',
	'INVITES-type-include' => 'plex',
	'INVITES-plexLibraries' => '',
	'INVITES-EmbyTemplate' => '',
	'INVITES-plex-tv-labels' => '',
	'INVITES-plex-music-labels' => '',
	'INVITES-plex-movies-labels' => '',
	'INVITES-allow-delete-include' => false,
	'INVITES-maximum-invites' => '0',
	'STRIPE-komga-enabled' => false,
	'STRIPE-komga-uri' => '',
	'STRIPE-komga-api-key' => '',
	'STRIPE-komga-default-user-password' => '',
	'STRIPE-komga-roles' => '',
	'STRIPE-komga-libraryIds' => '',
);
