<?php
return array(
    'branch' => 'v2-develop',
	'authType' => 'internal',
    'authBackend' => '',
	'authBackendHost' => '',
	'authUsername' => '',
	'authPassword' => '',
	'authBaseDN' => '',
	'authBackendDomain' => '',
    'logo' => 'plugins/images/organizr/logo-wide.png',
    'loginWallpaper' => '',
    'title' => 'Organizr V2',
    'useLogo' => false,
    'headerColor' => '',
    'headerTextColor' => '',
    'lockScreen' => false,
    'theme'=>'Organizr',
    'style'=>'dark',
    'plexURL' => '',
    'plexToken' => '',
    'plexID' => '',
    'tautulliURL' => '',
    'ombiURL' => '',
    'ssoPlex' => false,
    'ssoOmbi' => false,
    'ssoTautulli' => false
);
